---
title: "Marathon Analysis"
author: "Ryan Heitsmith"
date: "5/6/2017"
output: html_document
---
```{r}
library(googlesheets)
library(tidyverse)
```
```{r}
workouts <- read_csv("~/Downloads/workout_tracker - Sheet1.csv") %>%
  filter(Date < as.Date("2017-04-17"))

#clean a few vars
workouts$Pace <- workouts$Distance_miles / (workouts$Duration_min / 60)
workouts$min_per_mile <- 60 / workouts$Pace
workouts$Activity <- tolower(workouts$Activity)
```

```{r}
summary(workouts)
```

```{r}
#create some stats, print to console
active_days <- as.numeric(nrow(workouts[unique(workouts$Date), ]))
rest_days <- as.numeric((as.Date("2017-04-17") - min(workouts$Date)) - 97)
runs <- workouts %>% filter(Activity == "run") 
avg_run_pace <- round(mean(runs$Pace[!is.na(runs$Pace)]), 2)
avg_min_mile <- round(mean(runs$min_per_mile[!is.na(runs$min_per_mile)]), 0)

print(paste0("Active: ", active_days))
print(paste0("Rest: ", rest_days))
print(paste0("Average run pace of ", avg_run_pace, " mph or roughly ", avg_min_mile, " minutes pre mile."))
```

```{r}
table(workouts$Activity)
```

```{r}
ggplot(workouts, aes(Activity, fill = Activity)) +
  geom_bar(stat = "count") +
  theme_light() +
  scale_y_continuous(expand = c(0, 0)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "None") +
  scale_fill_manual(values = c("#a6cee3", "#1f78b4", "#b2df8a", "#33a02c", "#fb9a99", "#e31a1c", "#fdbf6f", "#ff7f00", "#cab2d6", "#6a3d9a", "#ffff99")) +
  labs(title = "Breakdown of Training Activity Days")
```
