---
title: "linkcomm_practice"
author: "Ryan Heitsmith"
date: "9/15/2017"
output: html_document
---
```{r, echo=FALSE}
#worked off examples from the linkcomm vignette: https://cran.r-project.org/web/packages/linkcomm/vignettes/linkcomm.pdf
#load the package
library(linkcomm)
```

```{r, echo=FALSE}
#load the lesmiserables dataset and take a look
lesmis <- lesmiserables
glimpse(lesmis)
```

Dataset is composed of two variables, the character name and the characters they appear on stage with in the stage production of LesMis.

```{r, echo=FALSE}
#plots a dendrogram, creates a linkcomm object that can be plotted
lc <- getLinkCommunities(lesmis)
```

```{r, echo=FALSE}
#create plots
fruchterman <- plot(lc, type = "graph", layout = layout.fruchterman.reingold)
spencer <- plot(lc, type = "graph", layout = "spencer.circle", shownodesin = 3)
comm_membership <- plot(lc, type = "members")

```

```{r, echo=FALSE}
#get community centrality scores for key characters. Higher numbers indicate greater and more important community membership within the network
cc <- getCommunityCentrality(lc)
head(sort(cc, decreasing = TRUE))
```

We might use this same tactic to identify the most central or connected members of a criminal enterprise to determine whose arrest will cause the greatest disruption to the network.